import type { Metadata } from "next";
import { Roboto, Roboto_Serif } from "next/font/google"
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInUrl={process.env.CLERK_SIGN_IN_URL}
      signUpUrl={process.env.CLERK_SIGN_UP_URL}
    >
      <html lang="en">
        <body
          className={roboto.className + ' text-[#FAFAFA] bg-[#09090B]'}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
